POST https://yatvms.azurewebsites.net/register-staff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbXkiLCJyb2xlIjoic2VjdXJpdHkiLCJpYXQiOjE3MDQyNTYyMzV9.u3udwSOH9q4avg-ow52ij8WV5Y7eLvnYWtJzp6Q0DqE

{
  "username": "mir",
  "password": "123" 
}
// staff registration

###

POST https://yatvms.azurewebsites.net/register-security
Content-Type: application/json

{
  "username": "yamy",
  "password": "123" 
}
// security registration

###

POST https://yatvms.azurewebsites.net/login-staff
Content-Type: application/json

{
  "username": "mir",
  "password": "123" 
}
// staff login

###

POST https://yatvms.azurewebsites.net/login-security
Content-Type: application/json

{
  "username": "yamy",
  "password": "123" 
}
// security login

###

POST https://yatvms.azurewebsites.net/appointments
Content-Type: application/json

{
  "name": "yat",
  "company": "ABC Corporation",
  "purpose": "meeting",
  "phoneNo": "011223344",
  "date": "26-6-2023",
  "time": "12:00AM",
  "verification": "N/A",
  "staff": {
    "username": "mir"
  }
}
// create appointment
###
GET https://yatvms.azurewebsites.net/appointments
// visitor can view

###

GET https://yatvms.azurewebsites.net/staff-appointments/mir
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODgwMzU3MTJ9.lUyhw3FKnJWCa6cO1c_J-mEsrcR8miNWXjo5DnSHNf0
// staff see appointment
###

PUT https://yatvms.azurewebsites.net/appointments/yat
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODgwMzUzMjR9.6wI_N4QpTqY-eixW3rzOsNew76vvlbPL3a2weZRcYsk
Content-Type: application/json

{ "verification": "verified" }
//staff update appointment
###

DELETE https://yatvms.azurewebsites.net/appointments/yat
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODc2ODM1NDh9.XkbTmIIEl9YSoZfuEJJCuhwDln_PU9pLrOktBOdVsok
//staff delete appointment
####


POST https://yatvms.azurewebsites.net/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODc3MDc4NTR9.7SH9XF5k48Zp4w0OQONs6nA0Enf0Rl1FMAb0DZD2fsU
Content-Type: application/json

{
  "username": "mir"
}
//logout staff